### ISSUE TITLE
Invalid control name generates cryptic error at runtime

### ISSUE THREAD

**Issue by tannerblair** [LabVIEW-DCAF/UIModules#16]
If a control name doesn't exist, the engine throws the following error:

"Error 1055 occurred at Property Node in ...   Possible reason(s):  LabVIEW object reference is invalid."

This should be changed to a more meaningful error or handled better.

**Comment by jwgorman** [comment]
Acceptance Criteria:
- Return an error saying this control not found.
- Error should say which one it could not find.

**Comment by theSloopJohnB** [comment]
I'm modifying the error to read like this:

![image](https://cloud.githubusercontent.com/assets/26978265/25628056/7a8b7e70-2f2a-11e7-9283-2d2b68209eb9.png)

**Comment by becega** [comment]
Looks Good, yes the important thing is to know which control has an issue. What will it do if 2 controls are invalid?

**Comment by theSloopJohnB** [comment]
Good point. I'll play around with a few more error conditions to see what kinds of errors I can get.

**Comment by theSloopJohnB** [comment]
I've been working on consolidating the validation steps for all channels into one step before we start to associate channels with front panel items. This lets us report all the errors we can find with the user's VI instead of one at a time.

Here's a sample of what it looks like:

![image](https://cloud.githubusercontent.com/assets/26978265/25758880/cd86b186-3195-11e7-85af-0d9352ad0653.png)

Here's the text of the error, since the window cuts it off:
"""
Possible reason(s):

Type mismatch detected

DCAF UI Module:

There was an error resolving references to your UI front panel, "UI.vi". 

The following channels you specified in your configuration do not have matching labels on your front panel:

no_matching_channel_1
no_matching_channel_2

The following channels you specified in your configuration do not have the same data type specified as their corresponding front panel item:

wrong_type_1
wrong_type_2
"""

Assuming you think this is a good direction, the next step is to add a test for this invalid configuration.
